language: php
dist: trusty
sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

git:
    depth: 1

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  # print what's installed and where by default
  - which phpunit && phpunit --version
  # install different phpunit versions via composer for different php versions
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
      composer require "phpunit/phpunit=5.7.*"
    else
      composer require "phpunit/phpunit=4.8.*"
    fi
  - |

script: ./vendor/bin/phpunit
